---
- hosts: dev
  remote_user: vagrant
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: true
    - name: install vim
      apt: pkg=vim state=latest
      sudo: true
    - name: install tmux
      apt: pkg=tmux state=latest
      sudo: true
    - name: Install virtualenv wrapper
      apt: pkg=virtualenvwrapper state=latest
      sudo: true
    - name: Install git
      apt: pkg=git state=latest
      sudo: true
    - name: install libmysqlclient-dev
      apt: pkg=libmysqlclient-dev state=latest
      sudo: true
    - name: Install python-dev
      apt: pkg=python-dev state=latest
      sudo: true
    - name: Copy over bashrc
      copy: src=files/bashrc dest=/home/vagrant/.bashrc
    - name: Copy over vimrc
      copy: src=files/vimrc dest=/home/vagrant/.vimrc
    - name: Copy over vim folder
      copy: src=files/vim/ dest=/home/vagrant/.vim/
    - name: Setup pathogen folders
      command: mkdir -p ~/.vim/autoload ~/.vim/bundle
    - name: Get pathogen
      command: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    - name: Get syntastic
      command: git clone --depth=1 https://github.com/scrooloose/syntastic.git chdir=/home/vagrant/.vim/bundle
